unpackaged/main/default/objects/Account/fields/Google_Drive_Folder_ID__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Folder_ID__c</fullName>
    <label>Google Drive Folder ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Business__c/fields/Related_Client__c.field-meta.xml
<CustomField>
    <fullName>Related_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Businesses</relationshipLabel>
    <relationshipName>Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Livevox_Integration_Configuration__c/Livevox_Integration_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Livevox Integration Configuration</label>
</CustomObject>

unpackaged/main/default/objects/Livevox_Integration_Configuration__c/fields/DT_Form_campaingId__c.field-meta.xml
<CustomField>
    <fullName>DT_Form_campaingId__c</fullName>
    <label>DT Form campaingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Livevox_Integration_Configuration__c/fields/DT_Form_DS_campaing_Id__c.field-meta.xml
<CustomField>
    <fullName>DT_Form_DS_campaing_Id__c</fullName>
    <label>DT Form DS campaing Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Livevox_Integration_Configuration__c/fields/sessionId__c.field-meta.xml
<CustomField>
    <fullName>sessionId__c</fullName>
    <label>sessionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
  public static Account createTestAccount() {
    Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Person Account')
      .getRecordTypeId();

    Account account = new Account(
      FirstName = 'John',
      LastName = 'Doe',
      RecordTypeId = recordTypeId
    );
    insert account;
    return account;
  }

  public static Business__c createTestBusiness(Id accountId) {
    Business__c business = new Business__c(Name = 'Doe Enterprises', Related_Client__c = accountId);
    insert business;
    return business;
  }

  public static Opportunity createTestOpportunity(Id accountId) {
    Opportunity opportunity = new Opportunity(
      Name = 'Test Opportunity',
      StageName = 'Prospecting',
      CloseDate = Date.today(),
      AccountId = accountId
    );
    insert opportunity;
    return opportunity;
  }

  public static Opportunity createTestOpportunityWithRecordType(
    Id accountId,
    String developerTypeName,
    String stageName
  ) {
    Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
      .get(developerTypeName)
      .getRecordTypeId();

    Opportunity opportunity = new Opportunity(
      Name = 'Test Opportunity',
      StageName = stageName,
      CloseDate = Date.today(),
      AccountId = accountId,
      RecordTypeId = oppRecordTypeId
    );
    insert opportunity;
    return opportunity;
  }

  public static Case createTestCase(Id opportunityId) {
    Case testCase = new Case(
      Subject = 'Test Case',
      Status = 'Open',
      Opportunity__c = opportunityId
    );
    insert testCase;
    return testCase;
  }

  //Create Second Trade Opportunities with Account without Google Drive Folder
  public static void insertAccountsWithOppsBulk() {
    Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Person Account')
      .getRecordTypeId();
    List<Account> accounts = new List<Account>();

    for (Integer i = 1; i < 100; i++) {
      accounts.add(
        new Account(
          FirstName = 'Test',
          LastName = ' Account GD ' + i,
          Google_Drive_Folder_ID__c = null,
          RecordTypeId = recordTypeId
        )
      );
    }
    insert accounts;

    Map<String, Id> accountIdMap = new Map<String, Id>();
    for (Account acc : [SELECT Id, Name FROM Account]) {
      accountIdMap.put(acc.Name, acc.Id);
    }

    Id secondTradeRecordTypeId = Schema.SObjectType.Opportunity
      .getRecordTypeInfosByName()
      .get('Second Trade')
      .getRecordTypeId();

    List<Opportunity> opportunities = new List<Opportunity>();
    for (Integer i = 1; i < 100; i++) {
      Id accountId = accountIdMap.get('Test Account GD ' + i);
      opportunities.add(
        new Opportunity(
          Name = 'Test Opportunity GD Second Trade ' + i,
          AccountId = accountId,
          StageName = 'Set Appointment',
          CloseDate = Date.today().addDays(30),
          RecordTypeId = secondTradeRecordTypeId
        )
      );
    }
    insert opportunities;
  }

  public static void insertAccountsBulk() {
    Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Person Account')
      .getRecordTypeId();
    List<Account> accounts = new List<Account>();

    for (Integer i = 1; i < 100; i++) {
      accounts.add(
        new Account(
          FirstName = 'Test',
          LastName = ' Account GD ' + i,
          Google_Drive_Folder_ID__c = null,
          RecordTypeId = recordTypeId
        )
      );
    }
    insert accounts;
  }

  public static void insertAccount(String firstName, String lastName) {
    Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
      .get('Person Account')
      .getRecordTypeId();
    Account account = new Account(
      FirstName = firstName,
      LastName = lastName,
      Google_Drive_Folder_ID__c = null,
      RecordTypeId = recordTypeId
    );
    insert account;
  }

  public static Id getOppRecordTypeId(String recordTypeName) {
    return Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get(recordTypeName)
      .getRecordTypeId();
  }

  public static Opportunity createOpportunity(String name, Id recordTypeId) {
    Opportunity opp = new Opportunity(
      Name = name,
      StageName = 'Prospecting',
      CloseDate = System.today().addDays(30),
      RecordTypeId = recordTypeId
    );
    insert opp;
    return opp;
  }

  public static bt_stripe__Payment_Schedule__c createPaymentSchedule(Id opportunityId) {
    bt_stripe__Payment_Schedule__c schedule = new bt_stripe__Payment_Schedule__c(
      Opportunity__c = opportunityId
    );
    insert schedule;
    return schedule;
  }

  public static bt_stripe__Transaction__c createTransaction(
    Id scheduleId,
    Id opportunityId,
    String status,
    Decimal amount
  ) {
    bt_stripe__Transaction__c trans = new bt_stripe__Transaction__c(
      bt_stripe__Transaction_Status__c = status,
      bt_stripe__Amount__c = amount,
      bt_stripe__Payment_Schedule__c = scheduleId,
      bt_stripe__Opportunity2__c = opportunityId,
      bt_stripe__Due_Date__c = System.today()
    );
    insert trans;
    return trans;
  }

  public static List<Lead> buildLeadRecords() {
    List<Lead> leads = new List<Lead>();
    leads.add(
      new Lead(
        FirstName = 'James',
        LastName = 'Bond',
        Email = 'james.bond@example.com',
        LeadSource = 'DT Form',
        Total_Tax_Debt__c = 50000,
        Status = 'Working',
        MobilePhone = '5555555555'
      )
    );
    return leads;
  }

  public static void createLivevoxConfiguration() {
    Livevox_Integration_Configuration__c existingSession = new Livevox_Integration_Configuration__c();
    existingSession.Name = 'ITR Session';
    existingSession.sessionId__c = '1234';
    existingSession.DT_Form_campaingId__c = '23455';
    existingSession.DT_Form_DS_campaing_Id__c = '32142';
    insert existingSession;
  }

    public static Task createTask(String subject) {
        Task testTask = new Task(Subject = subject);
        insert testTask;
        return testTask;
    }

    public static ContentVersion createContentVersion(String title, String pathOnClient, Blob versionData) {
        ContentVersion cv = new ContentVersion();
        cv.Title = title;
        cv.PathOnClient = pathOnClient;
        cv.VersionData = versionData;
        insert cv;
        return cv;
    }
}