unpackaged/main/default/objects/Lead/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Attempting Contact</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>NICE</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Currently in IA or CNC</fullName>
            </value>
            <value>
                <fullName>Debt Too Low</fullName>
            </value>
            <value>
                <fullName>Phone Solicitations</fullName>
            </value>
            <value>
                <fullName>IRS Inquiry</fullName>
            </value>
            <value>
                <fullName>State Debt Only</fullName>
            </value>
            <value>
                <fullName>Child Support</fullName>
            </value>
            <value>
                <fullName>Tax Question</fullName>
            </value>
            <value>
                <fullName>Credit Card Debt</fullName>
            </value>
            <value>
                <fullName>Cant Help</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Bad or Wrong Number</fullName>
            </value>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Student Loan</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Bad or Wrong Number: After Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Velocify_Id__c.field-meta.xml
<CustomField>
    <fullName>Velocify_Id__c</fullName>
    <label>Velocify Id</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/LivevoxCampaignRequestWrapperTest.cls
@isTest
private class LivevoxCampaignRequestWrapperTest {

    @TestSetup
    static void makeData(){
        Lead testLead = new Lead(
            FirstName = 'John',
            LastName = 'Doe',
            MobilePhone = '(650) 555-1234',
            ///Velocify_Id__c = '123456',
            Company = 'Test Company',
            Status = 'Working'
        );
        insert testLead;
    }
    @isTest
    static void testCampaignRequestWrapper() {
        Lead testLead = [SELECT Id, FirstName,LastName,Street,
        City,State,PostalCode,Phone,Email,LeadSource,MobilePhone,
        Total_Tax_Debt__c,CreatedDate,Status,Sub_Status__c
        FROM Lead WHERE FirstName ='John' LIMIT 1]; 

        LivevoxCampaignRequestWrapper wrapper = new LivevoxCampaignRequestWrapper(testLead);
        
        Assert.areEqual(1, wrapper.records.size(), 'Wrapper should contain one record');

        LivevoxCampaignRequestWrapper.CampaignRecord record = wrapper.records[0];

        
        Assert.areEqual('6505551234', record.phone1, 'Phone number should be formatted correctly');
        //Assert.areEqual(testLead.Velocify_Id__c, record.account, 'Account field should match the lead Velocify_Id__c');
        
    }

  
}