unpackaged/main/default/objects/Lead/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Attempting Contact</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>NICE</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Currently in IA or CNC</fullName>
            </value>
            <value>
                <fullName>Debt Too Low</fullName>
            </value>
            <value>
                <fullName>Phone Solicitations</fullName>
            </value>
            <value>
                <fullName>IRS Inquiry</fullName>
            </value>
            <value>
                <fullName>State Debt Only</fullName>
            </value>
            <value>
                <fullName>Child Support</fullName>
            </value>
            <value>
                <fullName>Tax Question</fullName>
            </value>
            <value>
                <fullName>Credit Card Debt</fullName>
            </value>
            <value>
                <fullName>Cant Help</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Bad or Wrong Number</fullName>
            </value>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Student Loan</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Bad or Wrong Number: After Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LivevoxIntegrationQueueable.cls
public class LivevoxIntegrationQueueable implements Queueable, Database.AllowsCallouts {

    private List<Lead> leadsToProcess;
    private Set<Id> leadsToProcessIds = new Set<Id>();
    private String triggerContext = '';

    public LivevoxIntegrationQueueable(List<Lead> leadsToProcess, String triggerContext) {
        this.leadsToProcess = leadsToProcess;
        this.triggerContext = triggerContext;
        for (Lead lead : leadsToProcess) {
            leadsToProcessIds.add(lead.Id);
        }

    }

    public void execute(QueueableContext context) {

        List<Lead> leads = [SELECT Id,FirstName,LastName,Street,
        City,State,PostalCode,Phone,Email,LeadSource,
        Total_Tax_Debt__c,CreatedDate,Status,Sub_Status__c, MobilePhone
        FROM Lead WHERE Id IN :leadsToProcessIds];

        //Validate this because we need to send the list of Leads instead of only one Lead at a time 
        for(Lead lead: leads){
            if(triggerContext == 'INSERT'){
                System.debug('queueable insert');
                LivevoxIntegrationService.createLivevoxContact(lead);
            } else if (triggerContext == 'UPDATE'){
                System.debug('queueable update');
                LivevoxIntegrationService.updateLivevoxContact(lead);
            }
            
        }
    }

}