unpackaged/main/default/objects/Web_Service_Setting__mdt/Web_Service_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Web Service Setting</label>
    <pluralLabel>Web Services Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Web_Service_Setting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/PersonAccountWebhookCallout.cls
public class PersonAccountWebhookCallout {
    
    private static Web_Service_Setting__mdt settings = Web_Service_Setting__mdt.getInstance('WebhookPersonAccounts');

    @future(callout=true)
    public static void sendPersonAccountData(String json) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(settings.Endpoint__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(json);
            
        try {
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                System.debug('Success: ' + response.getBody());
            } else {
                System.debug('Error WebhookPersonAccounts: ' + response.getStatusCode() + ' ' + response.getStatus());
            }
        } catch(Exception e) {
            System.debug('Exception WebhookPersonAccounts: ' + e.getMessage());
        }
    }
}