unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Status__c</fullName>
    <inlineHelpText>Displays the state of the funds. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Authorized funds will be &#39;Uncaptured&#39; after 7 days if not captured.</inlineHelpText>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Captured</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partially Refunded</fullName>
            </value>
            <value>
                <fullName>Uncaptured</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Dispute Warning</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Partially Reversed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/classes/TaskTriggerHandler.cls
public inherited sharing class TaskTriggerHandler extends TriggerHandler {
    public List<Task> newTasksList;
    public Map<Id, Task> oldTasksMap;
    
    public TaskTriggerHandler() {
        this.newTasksList = (List<Task>) Trigger.new;
        this.oldTasksMap = (Map<Id, Task>) Trigger.oldMap;
    }

    public override void afterInsert() {
        Set<Id> relatedCaseIds = new Set<Id>();
        Set<Id> relatedOppIds = new Set<Id>();
        Id currentUserId = UserInfo.getUserId();

        for (Task taskID : newTasksList) {
            if (taskID.WhatId != null && String.valueOf(taskID.WhatId).startsWith('500')) { 
                relatedCaseIds.add(taskID.WhatId);
            }
            if (taskID.WhatId != null && String.valueOf(taskID.WhatId).startsWith('006') && 
            (taskID.TaskSubtype == 'Call')) { 
                relatedOppIds.add(taskID.WhatId);
            }
        }
        
        if (!relatedCaseIds.isEmpty()) {
            Set<Id> ownerCaseIds = new Set<Id>();
            for (Case c : [SELECT Id FROM Case WHERE Id IN :relatedCaseIds AND OwnerId = :currentUserId]) {
                ownerCaseIds.add(c.Id);
            }
            
            if (!ownerCaseIds.isEmpty()) {
                LastInteractionHelper.updateLastInteractionField(ownerCaseIds);
            }
        }
        
        if (!relatedOppIds.isEmpty()) {
            filterOpportunitiesWithUncapturedTransactions(new List<Id>(relatedOppIds));
        }
    }
    

    public override void afterUpdate() {
        Set<Id> relatedCaseIds = new Set<Id>();
        Id currentUserId = UserInfo.getUserId();

        for (Task taskID : newTasksList) {
            if (taskID.WhatId != null && String.valueOf(taskID.WhatId).startsWith('500')) { 
                relatedCaseIds.add(taskID.WhatId);
            }
        }
        
        if (!relatedCaseIds.isEmpty()) {
            Set<Id> ownerCaseIds = new Set<Id>();
            for (Case c : [SELECT Id FROM Case WHERE Id IN :relatedCaseIds AND OwnerId = :currentUserId]) {
                ownerCaseIds.add(c.Id);
            }
            
            if (!ownerCaseIds.isEmpty()) {
                LastInteractionHelper.updateLastInteractionField(ownerCaseIds);
            }
        }
    }

    private static void filterOpportunitiesWithUncapturedTransactions(List<Id> oppIdList) {
        if (oppIdList.isEmpty()) {
            return;
        }
    
        List<Id> filteredOpportunityIds = new List<Id>();
    
        List<bt_stripe__Transaction__c> transactions = [
            SELECT Id, bt_stripe__Payment_Status__c, LastModifiedDate, bt_stripe__Opportunity2__r.Id  
            FROM bt_stripe__Transaction__c 
            WHERE bt_stripe__Payment_Status__c = 'Uncaptured' 
            AND bt_stripe__Due_Date__c = TODAY
            AND bt_stripe__Opportunity2__r.Id IN :oppIdList
        ];
    
        for (bt_stripe__Transaction__c txn : transactions) {
            if (txn.bt_stripe__Opportunity2__r.Id != null) {
                filteredOpportunityIds.add(txn.bt_stripe__Opportunity2__r.Id);
            }
        }
        
        if (!filteredOpportunityIds.isEmpty()) {
            TaskTriggerHelper.TaskCallCounter(filteredOpportunityIds);
        }
    }
}