unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Currency_ISO__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Currency_ISO__c</fullName>
    <inlineHelpText>Select the currency to be used to process this transaction. Set automatically if only the Payment Gateway is selected. Must be set prior to processing the transaction.</inlineHelpText>
    <label>Currency ISO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Status__c</fullName>
    <inlineHelpText>Displays the state of the funds. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Authorized funds will be &#39;Uncaptured&#39; after 7 days if not captured.</inlineHelpText>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Captured</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partially Refunded</fullName>
            </value>
            <value>
                <fullName>Uncaptured</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Dispute Warning</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Partially Reversed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/DaysSinceLastOutreach__c.field-meta.xml
<CustomField>
    <fullName>DaysSinceLastOutreach__c</fullName>
    <formula>TODAY() -  LastOutreachDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Outreach</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/LastOutreachDate__c.field-meta.xml
<CustomField>
    <fullName>LastOutreachDate__c</fullName>
    <label>Last Outreach Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/CallRecaptureAttempts__c.field-meta.xml
<CustomField>
    <fullName>CallRecaptureAttempts__c</fullName>
    <label>Recapture Call Attempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/classes/TaskTriggerHandlerTest.cls
@isTest
private class TaskTriggerHandlerTest {
    
    @testSetup
    static void setupTestData() {

        Case testCase = new Case(Subject = 'Test Case');
        insert testCase;

        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today()
        );
        insert testOpportunity;

        bt_stripe__Transaction__c tran = new bt_stripe__Transaction__c(
            bt_stripe__Amount__c = 100,
            bt_stripe__Currency_ISO__c = 'USD',
            bt_stripe__Payment_Status__c = 'Uncaptured',
            bt_stripe__Opportunity2__c = testOpportunity.Id,
            bt_stripe__Due_Date__c = Date.today()
        );
        insert tran;
    }
    
    @isTest
    static void taskAfterInsertWithCaseTest() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Task task = new Task(
            WhatId = testCase.Id,
            Subject = 'Follow-up',
            Status = 'Not Started'
        );

        Test.startTest();
        insert task;
        Test.stopTest();

        Case updatedCase = [SELECT Id, DaysSinceLastOutreach__c, LastOutreachDate__c FROM Case LIMIT 1];
       Assert.areNotEqual(null, task.Id, 'The task should have been Insert.');
       Assert.areEqual(0, updatedCase.DaysSinceLastOutreach__c, 'The DaysSinceLastOutreach should be 0.');
    }
    
    @isTest
    static void taskAfterInsertWithOpportunityTest() {
        Opportunity testOpportunity = [SELECT Id, CallRecaptureAttempts__c FROM Opportunity LIMIT 1];

        Task task = new Task(
            WhatId = testOpportunity.Id,
            TaskSubtype = 'Call',
            Subject = 'Call with client',
            Status = 'Completed'
        );

        Test.startTest();
        insert task;
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Id, CallRecaptureAttempts__c FROM Opportunity WHERE Id = :testOpportunity.Id LIMIT 1];
        Assert.areNotEqual(null, task.Id, 'The task should have been updated.');
        Assert.isTrue(updatedOpp.CallRecaptureAttempts__c == 1, 'The CallRecaptureAttempts should be 1.');
    }

    @isTest
    static void taskAfterUpdateWithCaseTest() {
        Case testCase = [SELECT Id, LastOutreachDate__c FROM Case LIMIT 1];

        Task task = new Task(
            WhatId = testCase.Id,
            Subject = 'Initial Task',
            Status = 'Not Started'
        );
        insert task;

        task.Subject = 'Updated Task';

        Test.startTest();
        update task;
        Test.stopTest();

        Task updatedTask = [SELECT Id, Subject FROM Task WHERE Id = :task.Id LIMIT 1];
        case updateCase = [SELECT Id, LastOutreachDate__c FROM Case WHERE Id = :testCase.Id LIMIT 1];
        Assert.areEqual('Updated Task', updatedTask.Subject, 'The task should have been updated.');
        Assert.areEqual(date.today(), updateCase.LastOutreachDate__c, 'The LastOutreachDate should be match.');
    }
}