unpackaged/main/default/objects/Contact/fields/Total_Tax_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Debt__c</fullName>
    <label>Total Tax Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Attempting Contact</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>NICE</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Currently in IA or CNC</fullName>
            </value>
            <value>
                <fullName>Debt Too Low</fullName>
            </value>
            <value>
                <fullName>Phone Solicitations</fullName>
            </value>
            <value>
                <fullName>IRS Inquiry</fullName>
            </value>
            <value>
                <fullName>State Debt Only</fullName>
            </value>
            <value>
                <fullName>Child Support</fullName>
            </value>
            <value>
                <fullName>Tax Question</fullName>
            </value>
            <value>
                <fullName>Credit Card Debt</fullName>
            </value>
            <value>
                <fullName>Cant Help</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Bad or Wrong Number</fullName>
            </value>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Student Loan</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Bad or Wrong Number: After Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LivevoxIntegrationServiceTest.cls
@isTest
private class LivevoxIntegrationServiceTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createLivevoxConfiguration();

       
    }
    @isTest
    static void testCreateLivevoxContact() {
        List<Lead> leads = TestDataFactory.buildLeadRecords();
        insert leads;

        Test.startTest();
        RequestMock sessionMock = LivevoxSessionRequestMock.getSuccessSessionId();
        RequestMock livevoxContactMock = LivevoxIntegrationServiceMock.getContactCreateResponse();
        RequestMock sessionValidMock = LivevoxSessionRequestMock.getValidSession();
        RequestMock campaingMock = LivevoxCampaignRequestMock.appendContactToCampaign();

        Map<String,HttpCalloutMock> mockMap = new Map<String,HttpCalloutMock>();
        mockMap.put('callout/session/validate/1212', sessionValidMock);
        mockMap.put('callout/session/login', sessionMock);
        mockMap.put('callout/contact/contacts/', livevoxContactMock);
        mockMap.put('callout/campaign/campaigns/23455/transactions', campaingMock);
        
        HttpCalloutMock multiCalloutMock = new MultiRequestMock(mockMap);
        Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        LivevoxIntegrationService.createLivevoxContact(leads[0]);
        Test.stopTest();

        Assert.areEqual('DT Form' ,leads[0].LeadSource, 'LeadSource should be populated');
    }

    @isTest
    static void testUpdateLivevoxContact() {
        List<Lead> leads = TestDataFactory.buildLeadRecords();

        insert leads;

        Lead updateLead = [SELECT Id,FirstName,LastName,Street,
                            City,State,PostalCode,Phone,Email,LeadSource,
                            Total_Tax_Debt__c,CreatedDate,Status,Sub_Status__c, 
                            MobilePhone FROM Lead WHERE Id = :leads[0].Id];
        updateLead.LeadSource = 'DT Form DS';
        update updateLead;

        Test.startTest();
        RequestMock sessionMock = LivevoxSessionRequestMock.getSuccessSessionId();
        RequestMock livevoxContactMock = LivevoxIntegrationServiceMock.getContactCreateResponse();
        RequestMock sessionValidMock = LivevoxSessionRequestMock.getValidSession();
        RequestMock campaingMock = LivevoxCampaignRequestMock.appendContactToCampaign();

        Map<String,HttpCalloutMock> mockMap = new Map<String,HttpCalloutMock>();
        mockMap.put('callout/session/validate/1212', sessionValidMock);
        mockMap.put('callout/session/login', sessionMock);
        mockMap.put('callout/contact/contacts/', livevoxContactMock);
        mockMap.put('callout/campaign/campaigns/23455/transactions', campaingMock);
        
        HttpCalloutMock multiCalloutMock = new MultiRequestMock(mockMap);
        Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        LivevoxIntegrationService.updateLivevoxContact(updateLead);
        Test.stopTest();

        
        Assert.areEqual('DT Form DS', updateLead.LeadSource, 'Field was not updated correctly');
    }

@isTest
static void appendContactToCampaignTest(){
    List<Lead> leads = TestDataFactory.buildLeadRecords();

    
    Test.startTest();
    RequestMock campaingMock = LivevoxCampaignRequestMock.appendContactToCampaign();
    Test.setMock(HttpCalloutMock.class, campaingMock);
    LivevoxIntegrationService.appendContactToCampaign('1234556', leads[0]);
    Test.stopTest();

   }
}