unpackaged/main/default/objects/API_Configuration__mdt/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <label>API Version</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/API_Configuration__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/APIConfigurationHelper.cls
public with sharing class APIConfigurationHelper {
    public static APIConfiguration getConfiguration(String configName) {
        API_Configuration__mdt config = API_Configuration__mdt.getInstance(configName);

        if (Test.isRunningTest()) {
            config = new API_Configuration__mdt(
                        Token__c = 'sampleToken',
                        API_Version__c = '1.0',
                        MasterLabel = 'PitbullTaxAPI'
                    );
        }

        if (config == null) {
            throw new CustomException('API Configuration not found for: ' + configName);
        }
        
        return new APIConfiguration(config.Token__c, config.API_Version__c);
    }
}