unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

unpackaged/main/default/classes/TransactionTriggerHandler.cls
public with sharing class TransactionTriggerHandler extends TriggerHandler{

    public static Group queue = getQueueByName('2nd Trade – 1st Payment Declined');
    public static List<String> queueEmails = new List<String>{queue.Email};
    public List<bt_stripe__Transaction__c> newTransactions;
    public Map<Id, bt_stripe__Transaction__c> oldTransactionsMap;
    
    public TransactionTriggerHandler(){
        this.newTransactions = (List<bt_stripe__Transaction__c>) trigger.new;
        this.oldTransactionsMap = (Map<Id, bt_stripe__Transaction__c>) trigger.oldMap;
    }
    
    public override void afterInsert(){
        validateTransaction(this.newTransactions);
    
    }
	
    public override void afterUpdate(){
        List<bt_stripe__Transaction__c> transactions = this.newTransactions;
        Map<Id, bt_stripe__Transaction__c> transactionMap = this.oldTransactionsMap;
        List<Task> tasksToCreate = new List<Task>();
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();

        Map<Id, Opportunity> opportunityMap = fetchSecondTradeOpportunities(transactions);
        Map<Id, List<bt_stripe__Transaction__c>> scheduleTransactionsMap = fetchAllScheduleTransactions(transactions);

        for (bt_stripe__Transaction__c tr : transactions) {
            Opportunity relatedOpportunity = opportunityMap.get(tr.bt_stripe__Opportunity2__c);
            if (relatedOpportunity == null) {
                continue;
            }

            if (this.isTransactionFailed(tr, transactionMap)) {
                List<bt_stripe__Transaction__c> scheduleTransactions = scheduleTransactionsMap.get(tr.bt_stripe__Payment_Schedule__c);
                if (scheduleTransactions != null && !scheduleTransactions.isEmpty() && scheduleTransactions[0].Id == tr.Id) {
                    tasksToCreate.add(createTaskForTransaction(tr, relatedOpportunity, queue.Id));
                    emailsToSend.addAll(createEmails(tr, relatedOpportunity));
                }
            }
        }

        createTasks(tasksToCreate);
        sendEmails(emailsToSend);

        validateTransaction(this.newTransactions);
    
    }
    

    private Boolean isTransactionFailed(bt_stripe__Transaction__c trans, Map<Id, bt_stripe__Transaction__c> transactionMap) {
        return trans.bt_stripe__Transaction_Status__c == 'Failed' && 
               transactionMap.get(trans.Id).bt_stripe__Transaction_Status__c != 'Failed';
    }

    private static Map<Id, List<bt_stripe__Transaction__c>> fetchAllScheduleTransactions(List<bt_stripe__Transaction__c> transactions) {
        Set<Id> paymentScheduleIds = new Set<Id>();
        for (bt_stripe__Transaction__c tr : transactions) {
            if (tr.bt_stripe__Payment_Schedule__c != null) {
                paymentScheduleIds.add(tr.bt_stripe__Payment_Schedule__c);
            }
        }

        Map<Id, List<bt_stripe__Transaction__c>> scheduleTransactionsMap = new Map<Id, List<bt_stripe__Transaction__c>>();
        for (bt_stripe__Transaction__c tr : [SELECT Id, bt_stripe__Due_Date__c, bt_stripe__Payment_Schedule__c 
                                             FROM bt_stripe__Transaction__c 
                                             WHERE bt_stripe__Payment_Schedule__c IN :paymentScheduleIds 
                                             ORDER BY bt_stripe__Due_Date__c ASC]) {
            if (!scheduleTransactionsMap.containsKey(tr.bt_stripe__Payment_Schedule__c)) {
                scheduleTransactionsMap.put(tr.bt_stripe__Payment_Schedule__c, new List<bt_stripe__Transaction__c>());
            }
            scheduleTransactionsMap.get(tr.bt_stripe__Payment_Schedule__c).add(tr);
        }
        return scheduleTransactionsMap;
    }

    private static Group getQueueByName(String queueName) {
        return [SELECT Id, Email FROM Group WHERE Type = 'Queue' AND Name = :queueName LIMIT 1];
    }

    private static Map<Id, Opportunity> fetchSecondTradeOpportunities(List<bt_stripe__Transaction__c> transactions) {
        Set<Id> opportunityIds = new Set<Id>();
        for (bt_stripe__Transaction__c tr : transactions) {
            if (tr.bt_stripe__Opportunity2__c != null) {
                opportunityIds.add(tr.bt_stripe__Opportunity2__c);
            }
        }

        return new Map<Id, Opportunity>(
            [SELECT Id, Name, RecordType.Name 
             FROM Opportunity 
             WHERE Id IN :opportunityIds AND RecordType.Name = 'Second Trade']
        );
    }

    private static Task createTaskForTransaction(bt_stripe__Transaction__c trans, Opportunity opportunity, Id queueId) {
        return new Task(
            WhatId = opportunity.Id,
            OwnerId = queueId,
            Subject = '1st Payment Declined - ' + opportunity.Name + ' - US$' + trans.bt_stripe__Amount__c,
            Priority = 'Urgent',
            ActivityDate = System.today()
        );
    }

    private static List<Messaging.SingleEmailMessage> createEmails(bt_stripe__Transaction__c trans, Opportunity opportunity) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        String opportunityUrl = baseUrl + '/' + opportunity.Id;
       
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(queueEmails);
        email.setSubject('1st Payment Declined - ' + opportunity.Name + ' - $US' + trans.bt_stripe__Amount__c);
        email.setPlainTextBody('Greetings,\n\nThe first payment for Second Trade Opportunity "' + opportunity.Name +
        '" has failed.\nLink to Opportunity: ' + opportunityUrl + '\n\nPlease review the related task and follow up '+
        'with your opportunity team. \n\nRegards,\nSalesforce System');
        email.setSaveAsActivity(false);
        emails.add(email);
        return emails;
    }

    private static void createTasks(List<Task> tasks) {
        if (!tasks.isEmpty()) {
            try {
                insert tasks;
            } catch (Exception e) {
                System.debug('Error inserting tasks: ' + e.getMessage());
            }
        }
    }

    private static void sendEmails(List<Messaging.SingleEmailMessage> emails) {
        if (!emails.isEmpty()) {
            try {
                Messaging.sendEmail(emails);
            } catch (Exception e) {
                System.debug('Error sending emails: ' + e.getMessage());
            }
        }
    }

    private static void validateTransaction(List<bt_stripe__Transaction__c> trans) {
        List<bt_stripe__Transaction__c> validTransactions = new List<bt_stripe__Transaction__c>();
        
        for (bt_stripe__Transaction__c txn : trans) {
            if (txn.bt_stripe__Transaction_Status__c == 'Completed' && txn.bt_stripe__Payment_Schedule__c != null) {
                validTransactions.add(txn);
            }
        }
        
        if (!validTransactions.isEmpty()) {
            PaymentScheduleHelper.processTransactions(validTransactions);
        }
    }
    
}