unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Scheduled_Transactions_Amount__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Transactions_Amount__c</fullName>
    <label>Scheduled Transactions Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Parent_Transaction__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Parent_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Auto-populated if a refund transaction was processed, referencing the originally captured transaction.</inlineHelpText>
    <label>Original Transaction (If Refund)</label>
    <referenceTo>bt_stripe__Transaction__c</referenceTo>
    <relationshipLabel>Refunds</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TransactionScheduledAmountBatch.cls
public class TransactionScheduledAmountBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, Scheduled_Transactions_Amount__c,
                   (SELECT Id, bt_stripe__Amount__c 
                    FROM bt_stripe__Transactions__r 
                    WHERE bt_stripe__Transaction_Status__c = 'Open')
            FROM bt_stripe__Payment_Schedule__c 
            WHERE Id IN (
                SELECT bt_stripe__Payment_Schedule__c 
                FROM bt_stripe__Transaction__c 
                WHERE bt_stripe__Transaction_Status__c = 'Open'
                AND bt_stripe__Payment_Schedule__c != null
            )
        ]);
    }
    
    public void execute(Database.BatchableContext BC, List<bt_stripe__Payment_Schedule__c> scope) {
        List<bt_stripe__Payment_Schedule__c> psToUpdate = new List<bt_stripe__Payment_Schedule__c>();
        
        for(bt_stripe__Payment_Schedule__c ps : scope) {
            Decimal totalAmount = 0;
            
            for(bt_stripe__Transaction__c trans : ps.bt_stripe__Transactions__r) {
                totalAmount += trans.bt_stripe__Amount__c ?? 0;
            }
            
            ps.Scheduled_Transactions_Amount__c = totalAmount;
            psToUpdate.add(ps);
        }
        
        update psToUpdate;
    }
    
    public void finish(Database.BatchableContext BC) {}
}