unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Status__c</fullName>
    <description>The status of Payments across the overall Schedule. Updated automatically.</description>
    <inlineHelpText>The status of Payments across the overall Schedule. Updated automatically.</inlineHelpText>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Good Standing</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Failed to Collect</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Refunded</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Status__c</fullName>
    <inlineHelpText>Displays the state of the funds. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Authorized funds will be &#39;Uncaptured&#39; after 7 days if not captured.</inlineHelpText>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Captured</fullName>
            </value>
            <value>
                <fullName>Partially Captured</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partially Refunded</fullName>
            </value>
            <value>
                <fullName>Uncaptured</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Dispute Warning</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Partially Reversed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/First_Completed_Captured_Transaction__c.field-meta.xml
<CustomField>
    <fullName>First_Completed_Captured_Transaction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Completed/Captured Transaction</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/First_Pay_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Pay_Date__c</fullName>
    <label>First Pay Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/FirstCompletedCapturedTransactionBatch.cls
public class FirstCompletedCapturedTransactionBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id FROM bt_stripe__Payment_Schedule__c WHERE Id IN ' +
                        '(SELECT bt_stripe__Payment_Schedule__c FROM bt_stripe__Transaction__c ' +
                        'WHERE bt_stripe__Payment_Schedule__c != null ' +
                        'AND bt_stripe__Transaction_Status__c = \'Completed\' ' +
                        'AND bt_stripe__Payment_Status__c = \'Captured\' ' +
                        'AND bt_stripe__Due_Date__c != null)';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<bt_stripe__Payment_Schedule__c> paymentSchedules) {
        List<bt_stripe__Transaction__c> transactionsToUpdate = new List<bt_stripe__Transaction__c>();
        Map<Id, Opportunity> opportunitiesToUpdateMap = new Map<Id, Opportunity>();
        
        Set<Id> paymentScheduleIds = new Set<Id>();
        for (bt_stripe__Payment_Schedule__c ps : paymentSchedules) {
            paymentScheduleIds.add(ps.Id);
        }
        
        Map<Id, List<bt_stripe__Transaction__c>> transactionsByPaymentSchedule = new Map<Id, List<bt_stripe__Transaction__c>>();
        
        List<bt_stripe__Transaction__c> allTransactions = [
            SELECT Id, bt_stripe__Payment_Schedule__c, bt_stripe__Transaction_Status__c, 
                    bt_stripe__Payment_Status__c, bt_stripe__Due_Date__c, bt_stripe__Amount__c,
                    First_Completed_Captured_Transaction__c, bt_stripe__Opportunity2__c, 
                    CreatedDate
            FROM bt_stripe__Transaction__c 
            WHERE bt_stripe__Payment_Schedule__c IN :paymentScheduleIds
            AND bt_stripe__Transaction_Status__c = 'Completed'
            AND bt_stripe__Payment_Status__c = 'Captured'
            AND bt_stripe__Due_Date__c != null
            ORDER BY bt_stripe__Payment_Schedule__c, bt_stripe__Due_Date__c ASC
        ];
        
        for (bt_stripe__Transaction__c trans : allTransactions) {
            if (!transactionsByPaymentSchedule.containsKey(trans.bt_stripe__Payment_Schedule__c)) {
                transactionsByPaymentSchedule.put(trans.bt_stripe__Payment_Schedule__c, new List<bt_stripe__Transaction__c>());
            }
            transactionsByPaymentSchedule.get(trans.bt_stripe__Payment_Schedule__c).add(trans);
        }
        
        for (Id paymentScheduleId : transactionsByPaymentSchedule.keySet()) {
            List<bt_stripe__Transaction__c> transactions = transactionsByPaymentSchedule.get(paymentScheduleId);
            
            if (!transactions.isEmpty()) {
                transactions.sort(new TransactionDateComparator());
                
                for (bt_stripe__Transaction__c trans : transactions) {
                    if (trans.First_Completed_Captured_Transaction__c == true) {
                        trans.First_Completed_Captured_Transaction__c = false;
                        transactionsToUpdate.add(trans);
                    }
                }
                
                if (transactions[0].First_Completed_Captured_Transaction__c == false) {
                    transactions[0].First_Completed_Captured_Transaction__c = true;
                    Boolean alreadyAdded = false;
                    for (bt_stripe__Transaction__c transToUpdate : transactionsToUpdate) {
                        if (transToUpdate.Id == transactions[0].Id) {
                            transToUpdate.First_Completed_Captured_Transaction__c = true;
                            alreadyAdded = true;
                            break;
                        }
                    }
                    if (!alreadyAdded) {
                        transactionsToUpdate.add(transactions[0]);
                    }
                    
                    // Update the related Opportunity's First_Pay_Date__c
                    if (transactions[0].bt_stripe__Opportunity2__c != null) {
                        opportunitiesToUpdateMap.put(transactions[0].bt_stripe__Opportunity2__c, new Opportunity(
                            Id = transactions[0].bt_stripe__Opportunity2__c,
                            First_Pay_Date__c = transactions[0].CreatedDate
                        ));
                        
                        System.debug('Adding Opportunity to update: ' + transactions[0].bt_stripe__Opportunity2__c + 
                                    ', First_Pay_Date__c: ' + transactions[0].CreatedDate);
                    }
                }
            }
        }
        
        // Update Transactions
        if (!transactionsToUpdate.isEmpty()) {
            try {
                update transactionsToUpdate;
                System.debug('Successfully updated ' + transactionsToUpdate.size() + ' transactions');
                
                for (bt_stripe__Transaction__c trans : transactionsToUpdate) {
                    System.debug('Updated Transaction: ' + trans.Id + 
                                ', Payment Schedule: ' + trans.bt_stripe__Payment_Schedule__c + 
                                ', First_Completed_Captured: ' + trans.First_Completed_Captured_Transaction__c);
                }
            } catch (Exception e) {
                System.debug('Error updating transactions: ' + e.getMessage());
                System.debug('Stack trace: ' + e.getStackTraceString());
            }
        } else {
            System.debug('No transactions needed to be updated');
        }
        
        // Update Opportunities
        if (!opportunitiesToUpdateMap.isEmpty()) {
            List<Opportunity> opportunitiesToUpdate = opportunitiesToUpdateMap.values();
            System.debug('=== ABOUT TO UPDATE OPPORTUNITIES ===');
            System.debug('Number of opportunities to update: ' + opportunitiesToUpdate.size());
            
            for (Opportunity opp : opportunitiesToUpdate) {
                System.debug('Before Update - Opportunity: ' + opp.Id + ', First_Pay_Date__c: ' + opp.First_Pay_Date__c);
            }
            
            try {
                Database.SaveResult[] saveResults = Database.update(opportunitiesToUpdate, false);
                Integer successCount = 0;
                Integer errorCount = 0;
                
                for(Integer i = 0; i < saveResults.size(); i++) {
                    if(saveResults[i].isSuccess()) {
                        successCount++;
                    } else {
                        errorCount++;
                        System.debug('Error updating Opportunity ' + opportunitiesToUpdate[i].Id + ': ' + saveResults[i].getErrors());
                    }
                }
                
                System.debug('Successfully updated ' + successCount + ' opportunities, ' + errorCount + ' errors');
                
                // Query back to verify the update actually worked
                List<Opportunity> verifyOpps = [
                    SELECT Id, First_Pay_Date__c 
                    FROM Opportunity 
                    WHERE Id IN :opportunitiesToUpdateMap.keySet()
                ];
                
                System.debug('=== VERIFICATION AFTER UPDATE ===');
                for (Opportunity opp : verifyOpps) {
                    System.debug('After Update - Opportunity: ' + opp.Id + ', First_Pay_Date__c: ' + opp.First_Pay_Date__c);
                }
                
            } catch (Exception e) {
                System.debug('Error updating opportunities: ' + e.getMessage());
                System.debug('Stack trace: ' + e.getStackTraceString());
            }
        } else {
            System.debug('No opportunities needed to be updated');
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        System.debug('FirstCompletedCapturedTransactionBatch process completed.');
    }
    
    public class TransactionDateComparator implements Comparator<bt_stripe__Transaction__c> {
        public Integer compare(bt_stripe__Transaction__c t1, bt_stripe__Transaction__c t2) {
            if (t1.bt_stripe__Due_Date__c == null && t2.bt_stripe__Due_Date__c == null) {
                return 0;
            }
            if (t1.bt_stripe__Due_Date__c == null) {
                return 1;
            }
            if (t2.bt_stripe__Due_Date__c == null) {
                return -1;
            }
            
            if (t1.bt_stripe__Due_Date__c < t2.bt_stripe__Due_Date__c) {
                return -1;
            } else if (t1.bt_stripe__Due_Date__c > t2.bt_stripe__Due_Date__c) {
                return 1;
            } else {
                return 0;
            }
        }
    }
}