unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <label>Last Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Processed_Date__c</fullName>
    <inlineHelpText>The date this transaction was processed. Set automatically.</inlineHelpText>
    <label>Processed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdatePaymentScheduleBatchTest.cls
@isTest
private class UpdatePaymentScheduleBatchTest {
    
    @testSetup
    static void setupData() {
        List<bt_stripe__Payment_Schedule__c> schedules = new List<bt_stripe__Payment_Schedule__c>();
        for (Integer i = 0; i < 5; i++) {
            bt_stripe__Payment_Schedule__c schedule = new bt_stripe__Payment_Schedule__c();
            schedules.add(schedule);
        }
        insert schedules;

        List<bt_stripe__Transaction__c> transactions = new List<bt_stripe__Transaction__c>();
        for (bt_stripe__Payment_Schedule__c schedule : schedules) {
            bt_stripe__Transaction__c trans = new bt_stripe__Transaction__c(
                bt_stripe__Payment_Schedule__c = schedule.Id,
                bt_stripe__Transaction_Status__c = 'Completed',
                bt_stripe__Amount__c = 150.00,
                bt_stripe__Processed_Date__c = System.now() 
            );
            transactions.add(trans);
        }
        insert transactions;
    }
    
    static testMethod void testBatchExecution() {
        // Inicia la prueba
        Test.startTest();
        UpdatePaymentScheduleBatch batchJob = new UpdatePaymentScheduleBatch();
        Database.executeBatch(batchJob, 200);
        Test.stopTest();
        
        List<bt_stripe__Payment_Schedule__c> updatedSchedules = [SELECT Id, Last_Payment_Date__c, Last_Payment_Amount__c FROM bt_stripe__Payment_Schedule__c];

        for (bt_stripe__Payment_Schedule__c schedule : updatedSchedules) {
            Assert.areNotEqual(null, schedule.Last_Payment_Date__c, 'El campo Last_Payment_Date__c debe tener valor');
            Assert.areEqual(150.00, schedule.Last_Payment_Amount__c, 'El campo Last_Payment_Amount__c debe ser 150.00');
        }
    }
}