unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/First_Payment_Declined__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Payment Declined</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/Opportunity_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type__c</fullName>
    <formula>bt_stripe__Opportunity2__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Record Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FirstPaymentDeclinedServiceTest.cls
@isTest
private class FirstPaymentDeclinedServiceTest {
    
    @TestSetup
    static void setup() {
        RecordType secondTradeRT = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'Second Trade' LIMIT 1];
        
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        List<Opportunity> opportunities = new List<Opportunity>{
            new Opportunity(
                Name = 'Second Trade Opp 1',
                AccountId = testAccount.Id,
                StageName = 'Closed Won',
                CloseDate = Date.today(),
                RecordTypeId = secondTradeRT.Id
            ),
            new Opportunity(
                Name = 'Second Trade Opp 2',
                AccountId = testAccount.Id,
                StageName = 'Closed Won',
                CloseDate = Date.today(),
                RecordTypeId = secondTradeRT.Id
            )
        };
        insert opportunities;
        
        List<bt_stripe__Payment_Schedule__c> paymentSchedules = new List<bt_stripe__Payment_Schedule__c>{
            new bt_stripe__Payment_Schedule__c(
                Opportunity__c = opportunities[0].Id
            ),
            new bt_stripe__Payment_Schedule__c(
                Opportunity__c = opportunities[1].Id
            )
        };
        insert paymentSchedules;
        
        List<bt_stripe__Transaction__c> transactions = new List<bt_stripe__Transaction__c>();
        
        for (Integer i = 0; i < 2; i++) {
            transactions.add(new bt_stripe__Transaction__c(
                bt_stripe__Payment_Schedule__c = paymentSchedules[0].Id,
                bt_stripe__Opportunity2__c = opportunities[0].Id,
                bt_stripe__Transaction_Status__c = 'Open',
                bt_stripe__Due_Date__c = Date.today().addDays(i),
                bt_stripe__Amount__c = 1000
            ));
        }
        
        transactions.add(new bt_stripe__Transaction__c(
            bt_stripe__Payment_Schedule__c = paymentSchedules[1].Id,
            bt_stripe__Opportunity2__c = opportunities[1].Id,
            bt_stripe__Transaction_Status__c = 'Open',
            bt_stripe__Due_Date__c = Date.today(),
            bt_stripe__Amount__c = 1000
        ));
        
        insert transactions;
    }
    
    @isTest
    static void testFirstFailedTransactionMarked() {
        bt_stripe__Transaction__c trans = [
            SELECT Id, bt_stripe__Transaction_Status__c
            FROM bt_stripe__Transaction__c
            WHERE Opportunity_Record_Type__c = 'Second Trade'
            LIMIT 1
        ];
        
        Test.startTest();
        trans.bt_stripe__Transaction_Status__c = 'Failed';
        update trans;
        Test.stopTest();
        
        bt_stripe__Transaction__c result = [
            SELECT First_Payment_Declined__c
            FROM bt_stripe__Transaction__c
            WHERE Id = :trans.Id
        ];
        
        System.assertEquals(true, result.First_Payment_Declined__c, 
                          'First failed transaction should be marked');
    }
    
    @isTest
    static void testSecondFailedTransactionNotMarked() {
        List<bt_stripe__Transaction__c> transList = [
            SELECT Id, bt_stripe__Transaction_Status__c, bt_stripe__Payment_Schedule__c
            FROM bt_stripe__Transaction__c
            WHERE Opportunity_Record_Type__c = 'Second Trade'
            ORDER BY bt_stripe__Due_Date__c
            LIMIT 2
        ];
        
        Test.startTest();
        transList[0].bt_stripe__Transaction_Status__c = 'Failed';
        update transList[0];
        Test.stopTest();
        
        transList[1].bt_stripe__Transaction_Status__c = 'Failed';
        update transList[1];
        
        bt_stripe__Transaction__c result = [
            SELECT First_Payment_Declined__c
            FROM bt_stripe__Transaction__c
            WHERE Id = :transList[1].Id
        ];
        
        System.assertEquals(false, result.First_Payment_Declined__c, 
                          'Second failed transaction should NOT be marked');
    }
    
    @isTest
    static void testBulkProcessing() {
        List<bt_stripe__Transaction__c> transList = [
            SELECT Id, bt_stripe__Transaction_Status__c
            FROM bt_stripe__Transaction__c
            WHERE Opportunity_Record_Type__c = 'Second Trade'
        ];
        
        for (bt_stripe__Transaction__c trans : transList) {
            trans.bt_stripe__Transaction_Status__c = 'Failed';
        }
        
        Test.startTest();
        update transList;
        Test.stopTest();
        
        Integer markedCount = [
            SELECT COUNT()
            FROM bt_stripe__Transaction__c
            WHERE Id IN :transList
            AND First_Payment_Declined__c = true
        ];
        
        System.assertEquals(2, markedCount, 
                          'Should mark one per Payment Schedule (2 schedules = 2 marked)');
    }
}