unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Last_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Amount__c</fullName>
    <label>Last Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Amount__c</fullName>
    <inlineHelpText>The total amount to be processed when the Process button is charged or when the auto-charge process runs.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PaymentScheduleHelper.cls
public class PaymentScheduleHelper {
    public static void processTransactions(List<bt_stripe__Transaction__c> transactions) {
        Set<Id> paymentScheduleIds = new Set<Id>();
        Map<Id, bt_stripe__Transaction__c> transactionMap = new Map<Id, bt_stripe__Transaction__c>();
        
        for (bt_stripe__Transaction__c txn : transactions) {
            paymentScheduleIds.add(txn.bt_stripe__Payment_Schedule__c);
            transactionMap.put(txn.bt_stripe__Payment_Schedule__c, txn);
        }
        
        List<bt_stripe__Payment_Schedule__c> schedulesToUpdate = [
            SELECT Id, Last_Payment_Date__c, Last_Payment_Amount__c 
            FROM bt_stripe__Payment_Schedule__c
            WHERE Id IN :paymentScheduleIds
        ];
        
        for (bt_stripe__Payment_Schedule__c schedule : schedulesToUpdate) {
            bt_stripe__Transaction__c txn = transactionMap.get(schedule.Id);
            schedule.Last_Payment_Date__c = txn.LastModifiedDate.date(); 
            schedule.Last_Payment_Amount__c = txn.bt_stripe__Amount__c;
        }
        
        update schedulesToUpdate;
    }
}