unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/bt_stripe__Transaction__c.object-meta.xml
<CustomObject>
    <description>A Transaction is mainly used to charge or refund a Payment Method. These types of Transactions use the Charge Record Type. If you use Stripe, we create Payout Transactions from Webhook Events that come in nightly. If you use Stripe Connect, you can also create a Transfer or Payout Transaction for a Connected Account.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Due_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Due_Date__c</fullName>
    <inlineHelpText>Due date of the transaction. If Auto-Process is checked, this field is required.</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>bt_stripe__Payment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/bt_stripe__Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Transaction_Status__c</fullName>
    <inlineHelpText>Displays the state of the transaction, which controls business logic. Payment Status is only applicable when Transaction Status is &#39;Completed&#39;. Only &#39;Open&#39; and &#39;Canceled&#39; statuses should be set manually. See documentation for full status descriptions.</inlineHelpText>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Payment Intent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/First_Payment_Declined__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Payment Declined</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Transaction__c/fields/Opportunity_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type__c</fullName>
    <formula>bt_stripe__Opportunity2__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Record Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FirstPaymentDeclinedBackfillBatch.cls
public class FirstPaymentDeclinedBackfillBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, bt_stripe__Payment_Schedule__c, ' +
                      'bt_stripe__Transaction_Status__c, bt_stripe__Due_Date__c, ' +
                      'First_Payment_Declined__c, Opportunity_Record_Type__c ' +
                      'FROM bt_stripe__Transaction__c ' +
                      'WHERE bt_stripe__Transaction_Status__c = \'Failed\' ' +
                      'AND Opportunity_Record_Type__c = \'Second Trade\' ' +
                      'AND bt_stripe__Payment_Schedule__c != null ' +
                      'ORDER BY bt_stripe__Payment_Schedule__c, bt_stripe__Due_Date__c';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<bt_stripe__Transaction__c> scope) {
        List<bt_stripe__Transaction__c> transactionsToUpdate = new List<bt_stripe__Transaction__c>();
        Map<Id, Id> firstTransactionBySchedule = new Map<Id, Id>();
        
        for (bt_stripe__Transaction__c trans : scope) {
            if (!firstTransactionBySchedule.containsKey(trans.bt_stripe__Payment_Schedule__c)) {
                firstTransactionBySchedule.put(trans.bt_stripe__Payment_Schedule__c, trans.Id);
            }
        }
        
        for (bt_stripe__Transaction__c trans : scope) {
            if (firstTransactionBySchedule.get(trans.bt_stripe__Payment_Schedule__c) == trans.Id &&
                !trans.First_Payment_Declined__c) {
                
                transactionsToUpdate.add(new bt_stripe__Transaction__c(
                    Id = trans.Id,
                    First_Payment_Declined__c = true
                ));
            }
        }
        
        if (!transactionsToUpdate.isEmpty()) {
            Database.SaveResult[] results = Database.update(transactionsToUpdate, false);
            
            for (Integer i = 0; i < results.size(); i++) {
                if (!results[i].isSuccess()) {
                    System.debug('Error updating transaction ' + transactionsToUpdate[i].Id + ': ' + 
                               results[i].getErrors()[0].getMessage());
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext bc) {
        AsyncApexJob job = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                   TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob 
            WHERE Id = :bc.getJobId()
        ];
        
        System.debug('=== Batch Completed ===');
        System.debug('Status: ' + job.Status);
        System.debug('Items Processed: ' + job.JobItemsProcessed);
        System.debug('Errors: ' + job.NumberOfErrors);
    }
}