unpackaged/main/default/objects/bt_stripe__Payment_Method__c/bt_stripe__Payment_Method__c.object-meta.xml
<CustomObject>
    <description>A Payment Method record stores information about Credit Cards, Debit Cards and ACH Bank Accounts that are also in your Payment Gateway system. The Payment Method data is PCI compliant because it stores a token instead of raw card or bank data. Payment Methods are related to a Payment Gateway Customer and can be used to create charge Transactions.</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Expiration_Month__c</fullName>
    <inlineHelpText>The two digit value of the card&#39;s expiration month.</inlineHelpText>
    <label>Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Expiration_Year__c</fullName>
    <inlineHelpText>The two or four digit year of the card&#39;s expiration.</inlineHelpText>
    <label>Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Holder_Name__c</fullName>
    <inlineHelpText>The full name of the card or bank account holder (as displayed on the card or bank account).</inlineHelpText>
    <label>Holder&#39;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Number__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Number__c</fullName>
    <inlineHelpText>The full credit or debit card number.</inlineHelpText>
    <label>Number</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/bt_stripe__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>bt_stripe__Payment_Method__c.bt_stripe__Stripe_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.bt_stripe__Customer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>bt_stripe__Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Number__c</fullName>
    <label>Credit Card Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>4</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/CreateCreditCardPaymentMethod_Test.cls
@IsTest
public class CreateCreditCardPaymentMethod_Test {
 	@TestSetup
    static void makeData() {
       
        Account testAccount = TestUtility.createAccount('Test Account', 'Mortgage');
        insert testAccount;
       
        Contact testContact = TestUtility.createContact(testAccount.Id, 'Contact');
        insert testContact;

        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity', 'Qualification', Date.today());
        testOpportunity.Credit_Card_Number__c = '4111111111111111';
        testOpportunity.CVV__c = '123';
        insert testOpportunity;
    }

    @isTest
    static void createCreditPaymentMethod_createPaymentMethod_recordCreated() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        List<Opportunity> testOpportunityList = [SELECT Id, AccountId, ContactId FROM Opportunity LIMIT 1];

        List<CreateCreditCardPaymentMethod.InputParameters> inputList = new List<CreateCreditCardPaymentMethod.InputParameters>();
        CreateCreditCardPaymentMethod.InputParameters input = new CreateCreditCardPaymentMethod.InputParameters();
        input.opportunityId = testOpportunityList[0].Id;
        input.paymentMethodRT = Schema.SObjectType.bt_stripe__Payment_Method__c.getRecordTypeInfosByDeveloperName().get('Charge_Card').getRecordTypeId();
        input.cardholderName = 'John Doe';
        input.expiryMonth = '02';
        input.expiryYear = '24';
        input.postalCode = '12345';
        input.accountOpp = account.Id;
        input.contactOpp = contact.Id;
        inputList.add(input);

        Test.startTest();
            List<Id> paymentMethodIds = CreateCreditCardPaymentMethod.createPaymentMethod(inputList);
        Test.stopTest();

        assert.areNotEqual(0, paymentMethodIds.size(), 'Expected a payment method ID to be returned');
        
        bt_stripe__Payment_Method__c createdPaymentMethod = [
            SELECT Id, bt_stripe__Card_Holder_Name__c, bt_stripe__Card_Number__c,
                   bt_stripe__Card_Expiration_Month__c, bt_stripe__Card_Expiration_Year__c
            FROM bt_stripe__Payment_Method__c
            WHERE Id = :paymentMethodIds[0]
        ];
        
        assert.areEqual('John Doe', createdPaymentMethod.bt_stripe__Card_Holder_Name__c, 'Cardholder name mismatch');
        assert.areEqual('02', createdPaymentMethod.bt_stripe__Card_Expiration_Month__c, 'Expiry month mismatch');
        assert.areEqual('24', createdPaymentMethod.bt_stripe__Card_Expiration_Year__c, 'Expiry year mismatch');
    }

    @isTest
    static void createCreditPaymentMethod_createPaymentMethod_NullOpportunityId() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        List<Opportunity> testOpportunityList = [SELECT Id, AccountId, ContactId FROM Opportunity LIMIT 1];
        Boolean hasError = false;

        List<CreateCreditCardPaymentMethod.InputParameters> inputList = new List<CreateCreditCardPaymentMethod.InputParameters>();
        CreateCreditCardPaymentMethod.InputParameters input = new CreateCreditCardPaymentMethod.InputParameters();
        input.opportunityId = null;
        input.paymentMethodRT = Schema.SObjectType.bt_stripe__Payment_Method__c.getRecordTypeInfosByDeveloperName().get('Charge_Card').getRecordTypeId();
        input.cardholderName = 'John Doe';
        input.expiryMonth = '13';
        input.expiryYear = '20'; 
        input.postalCode = '12345';
        input.accountOpp = account.Id;
        input.contactOpp = contact.Id;
        inputList.add(input);

        Test.startTest();
            try {
                List<Id> paymentMethodIds = CreateCreditCardPaymentMethod.createPaymentMethod(inputList);
            } catch(Exception e) {
                hasError = true;
            }
        Test.stopTest();
        
        assert.isTrue(hasError, 'Expected an error due to invalid expiry data');
    }
    
}