unpackaged/main/default/objects/bt_stripe__Payment_Method__c/bt_stripe__Payment_Method__c.object-meta.xml
<CustomObject>
    <description>A Payment Method record stores information about Credit Cards, Debit Cards and ACH Bank Accounts that are also in your Payment Gateway system. The Payment Method data is PCI compliant because it stores a token instead of raw card or bank data. Payment Methods are related to a Payment Gateway Customer and can be used to create charge Transactions.</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Account__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce Business Account or Person Account related to this Payment Method.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Account_Holder_Type__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account_Holder_Type__c</fullName>
    <inlineHelpText>The type of entity that holds the account.</inlineHelpText>
    <label>Account Holder Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Personal Checking</fullName>
            </value>
            <value>
                <fullName>Business Checking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Account_Number__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account_Number__c</fullName>
    <inlineHelpText>The bank account number.</inlineHelpText>
    <label>Account Number</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Holder_Name__c</fullName>
    <inlineHelpText>The full name of the card or bank account holder (as displayed on the card or bank account).</inlineHelpText>
    <label>Holder&#39;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Contact__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce Contact related to this Payment Method.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Country_ISO__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Country_ISO__c</fullName>
    <inlineHelpText>Two-letter ISO code representing the country. 
- For cards, this is set automatically. 
- For ACH, this needs to be set manually.</inlineHelpText>
    <label>Country ISO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Currency_ISO__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Currency_ISO__c</fullName>
    <description>The currency paid out to the bank account must be selected on ACH creation.</description>
    <inlineHelpText>The currency paid out to the bank account must be selected on ACH creation.</inlineHelpText>
    <label>Currency ISO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Routing_Number__c</fullName>
    <inlineHelpText>The routing transit number for the bank account.</inlineHelpText>
    <label>Routing Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Send_to_Gateway__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Send_to_Gateway__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Payment Methods will process through the Payment Gateway unless this box is checked.</description>
    <inlineHelpText>Payment Methods will process through the Payment Gateway unless this box is checked.</inlineHelpText>
    <label>Send to Gateway</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/bt_stripe__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>bt_stripe__Payment_Method__c.bt_stripe__Stripe_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.bt_stripe__Customer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>bt_stripe__Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/CreateACHPaymentMethod.cls
public class CreateACHPaymentMethod {
    @InvocableMethod(label='Create ACH Payment Method' description='Creates a Payment Method of type ACH')
    public static List<Id> createPaymentMethod(List<InputParameters> inputList) {
        List<Id> paymentMethodIds = new List<Id>();
        
        if (!inputList.isEmpty()) {
            InputParameters input = inputList[0];
            List<EncryptedFieldsResultForAC> encryptedFields = getEncryptedFields(input.opportunityId);

            bt_stripe__Payment_Method__c newPaymentMethod = new bt_stripe__Payment_Method__c();
            newPaymentMethod.RecordTypeId = input.paymentMethodRT;
            newPaymentMethod.bt_stripe__Card_Holder_Name__c = input.cardholderName;
            newPaymentMethod.bt_stripe__Currency_ISO__c  = input.currencyIso;
            newPaymentMethod.bt_stripe__Country_ISO__c  = input.countryIso;
            newPaymentMethod.bt_stripe__Account_Holder_Type__c  = input.accountHolderType;
            newPaymentMethod.bt_stripe__Account__c = input.accountOpp;
            newPaymentMethod.bt_stripe__Contact__c = input.contactOpp;
            newPaymentMethod.bt_stripe__Send_to_Gateway__c = false;
             
            if (!encryptedFields.isEmpty()) {
                EncryptedFieldsResultForAC encryptedData = encryptedFields[0];
                newPaymentMethod.bt_stripe__Account_Number__c  = encryptedData.accountNumber;
                newPaymentMethod.bt_stripe__Routing_Number__c  = encryptedData.routingNumber;
            }

            if (Schema.sObjectType.bt_stripe__Payment_Method__c.isCreateable()) {
                try {
                    insert newPaymentMethod;
                    paymentMethodIds.add(newPaymentMethod.Id);
                } catch (DmlException e) {
                    throw new FlowException('Error creating ACH Payment Method: ' + e.getMessage());
                }
            } else {
                throw new FlowException('You do not have the necessary permissions to create a ACH Payment Method.');
            }
        }
        return paymentMethodIds;
    }

    public class InputParameters {
        @InvocableVariable(label='Opportunity ID' description='ID of the related Opportunity' required=true)
        public Id opportunityId;

        @InvocableVariable(label='Holders Name' description='Holders Name' required=true)
        public String cardholderName;

        @InvocableVariable(label='Account Holder Type' description='The Type of Holder Account' required=true)
        public String accountHolderType;

        @InvocableVariable(label='Currency ISO' description='The ISO Currency' required=true)
        public String currencyIso;
        
        @InvocableVariable(label='Country ISO' description='The ISO Country' required=true)
        public String countryIso;
        
        @InvocableVariable(label='Payment Method Record Type' description='Type of Payment Method Record Type' required=true)
        public String paymentMethodRT;
        
        @InvocableVariable(label='Account Related Opportunity' description='The Account associated to the Opportunity' required=true)
        public Id accountOpp;
        
        @InvocableVariable(label='Contact Related Opportunity' description='The Contact associated to the Opportunity' required=true)
        public Id contactOpp;
    }
    
    public class EncryptedFieldsResultForAC {
        public String accountNumber;
        public String routingNumber;
    }
    
   	private static List<EncryptedFieldsResultForAC> getEncryptedFields(Id opportunityId) {
        List<EncryptedFieldsResultForAC> results = new List<EncryptedFieldsResultForAC>();
        
        if (opportunityId == null) {
            return results;
        }

        if (!Schema.sObjectType.Opportunity.isAccessible()) {
            return results;
        }
        
        Schema.DescribeFieldResult creditCardNumberField = Opportunity.Account_Number__c.getDescribe();
        Schema.DescribeFieldResult cvvField = Opportunity.Routing_Number__c.getDescribe();
        
        if (!creditCardNumberField.isAccessible() ||!cvvField.isAccessible()) {
            return results;
        }
        
        List<Opportunity> opportunities = [
            SELECT Id,
                   Account_Number__c, 
                   Routing_Number__c 
            FROM Opportunity 
            WHERE Id = :opportunityId
        ];
        
        if (!opportunities.isEmpty()) {
            Opportunity opp = opportunities[0];
            EncryptedFieldsResultForAC result = new EncryptedFieldsResultForAC();
            
            result.accountNumber = opp.Account_Number__c;
            result.routingNumber = opp.Routing_Number__c;
            
            results.add(result);
        }
        
        return results;
    }
}