unpackaged/main/default/objects/bt_stripe__Payment_Method__c/bt_stripe__Payment_Method__c.object-meta.xml
<CustomObject>
    <description>A Payment Method record stores information about Credit Cards, Debit Cards and ACH Bank Accounts that are also in your Payment Gateway system. The Payment Method data is PCI compliant because it stores a token instead of raw card or bank data. Payment Methods are related to a Payment Gateway Customer and can be used to create charge Transactions.</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Account__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce Business Account or Person Account related to this Payment Method.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Contact__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce Contact related to this Payment Method.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Gateway__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Payment Gateway is the Gateway account that this Payment Method is related to. All subsequent transactions related to this Payment Method will be run through this Gateway.</inlineHelpText>
    <label>Payment Gateway</label>
    <referenceTo>bt_stripe__Payment_Gateway__c</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/bt_stripe__Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A Payment Schedule record allows you to generate recurring Open Transactions that will automatically be charged on a specified Date.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Account__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Contact__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Count__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Count__c</fullName>
    <description>The number of Transactions to generate. Optional if using an EZ Preset, Start, and End date.</description>
    <inlineHelpText>The number of Transactions to generate. Optional if using an EZ Preset, Start, and End date.</inlineHelpText>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Currency__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Currency__c</fullName>
    <description>The currency ISO value to set on each Transaction.</description>
    <inlineHelpText>The currency ISO value to set on each Transaction.</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Each_Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Each_Amount__c</fullName>
    <description>The amount to capture for each Transaction. Auto-calculated if there is a Total Amount and this field is blank.</description>
    <inlineHelpText>The amount to capture for each Transaction. Auto-calculated if there is a Total Amount and this field is blank.</inlineHelpText>
    <label>Each Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__End_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__End_Date__c</fullName>
    <description>The end date from which the logic is calculated. Can be the last Transaction date or the final date to calculate the series of Transactions with. Do not define if Recurrence Method is defined.</description>
    <inlineHelpText>The end date from which the logic is calculated. Can be the last Transaction date or the final date to calculate the series of Transactions with. Do not define if Recurrence Method is defined.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Initial_Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Initial_Amount__c</fullName>
    <description>If the initial amount should be a different amount than the &#39;Each Amount&#39; field. For ex., charging a $1,000 setup fee and each subsequent (each) payment is $500. Leave blank if all payment amounts are the same (just use Each Amount or Total Amount).</description>
    <inlineHelpText>If the initial amount should be a different amount than the &#39;Each Amount&#39; field. For ex., charging a $1,000 setup fee and each subsequent (each) payment is $500. Leave blank if all payment amounts are the same (just use Each Amount or Total Amount).</inlineHelpText>
    <label>Initial Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Gateway__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Payment Gateway is the Stripe account that transaction related to this Payment Schedule will use.</inlineHelpText>
    <label>Payment Gateway</label>
    <referenceTo>bt_stripe__Payment_Gateway__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Preset__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Preset__c</fullName>
    <description>The frequency of Transaction due date repetition. For ex., Daily sets each created Transaction to have a due date one day after the next. Monthly sets the Transactions to be due one month from each other.</description>
    <inlineHelpText>The frequency of Transaction due date repetition. For ex., Daily sets each created Transaction to have a due date one day after the next. Monthly sets the Transactions to be due one month from each other.</inlineHelpText>
    <label>EZ Preset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annually</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Recurrence_Method__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Recurrence_Method__c</fullName>
    <description>None = Fixed # Trans. Keep One Open = After 1 Trans completes, generate the &#39;next&#39; one on the same frequency.
                    Auto-renew = After all Trans are complete, generate the full Count again, such as 12 original, now 12 new future Trans.</description>
    <inlineHelpText>None = Fixed # Trans. Keep One Open = After 1 Trans completes, generate the &#39;next&#39; one on the same frequency.
                    Auto-renew = After all Trans are complete, generate the full Count again, such as 12 original, now 12 new future Trans.</inlineHelpText>
    <label>Recurrence Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keep One Open</fullName>
            </value>
            <value>
                <fullName>Auto-Renew</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Start_Date__c</fullName>
    <description>The first date from which the remainder of the logic is calculated. It can be the date of the first Transaction or the first date to calculate subsequent Transactions from.</description>
    <inlineHelpText>The first date from which the remainder of the logic is calculated. It can be the date of the first Transaction or the first date to calculate subsequent Transactions from.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/bt_stripe__Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Total_Amount__c</fullName>
    <inlineHelpText>The total amount of this Payment Schedule. Populate this value if the Each Amount field is blank. Leave this field blank if you have the Each Amount field populated. See documentation for more scenarios! Do not define if Recurrence Method is defined.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/bt_stripe__Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Gateway__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Gateway</label>
    <referenceTo>bt_stripe__Payment_Gateway__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PaymentScheduleGenQueuable.cls
public with sharing class PaymentScheduleGenQueuable implements Queueable, Database.AllowsCallouts {
    public InputParameters params;

    public PaymentScheduleGenQueuable(InputParameters params) {
        this.params = params;
    }
    
    @InvocableMethod(label='Create Payment Schedule' description='Creates Payment Schedules')
    public static void createPaymentSchedule(List<InputParameters> parameters) {
        if (!parameters.isEmpty()) {
            System.enqueueJob(new PaymentScheduleGenQueuable(parameters[0]));
        }
    }
    
    public void execute(QueueableContext context){
        
        try {
            bt_stripe__Payment_Schedule__c paymentSchedule = new bt_stripe__Payment_Schedule__c();
            //Information
            paymentSchedule.bt_stripe__Preset__c = params.ezPreset;
            paymentSchedule.bt_stripe__Recurrence_Method__c = params.recurrenceMethod;
            paymentSchedule.bt_stripe__Start_Date__c = params.startDate;
            paymentSchedule.bt_stripe__End_Date__c = params.endDate;
            paymentSchedule.bt_stripe__Count__c = params.count;
            paymentSchedule.Opportunity__c = params.opportunityId;
            paymentSchedule.bt_stripe__Initial_Amount__c = params.initialAmount;
            paymentSchedule.bt_stripe__Each_Amount__c = params.eachAmount;
            paymentSchedule.bt_stripe__Total_Amount__c = params.totalAmount;
            paymentSchedule.bt_stripe__Currency__c = params.currencyITR;
            paymentSchedule.bt_stripe__Description__c = params.description;
            //Related To
            paymentSchedule.bt_stripe__Payment_Gateway__c = params.paymentGateway;
            paymentSchedule.bt_stripe__Account__c = params.accountPs;
            paymentSchedule.bt_stripe__Contact__c = params.contactPs;
            paymentSchedule.bt_stripe__Payment_Method__c = params.paymentMethodPs;
            //Status
            paymentSchedule.bt_stripe__Payment_Status__c = params.paymentStatus;
            paymentSchedule.bt_stripe__Status__c = params.scheduleStatus;
            paymentSchedule.bt_stripe__Balance_Paid__c = params.balancePaid;
            paymentSchedule.bt_stripe__Balance_Due__c = params.balanceDue;
            paymentSchedule.bt_stripe__Next_Payment_Date__c =params.nextPaymentDate;

            //Schedule Details
            paymentSchedule.bt_stripe__Repeats__c = params.repeats;
            paymentSchedule.bt_stripe__Frequency__c = params.frequency;
            paymentSchedule.bt_stripe__Day_of_Month__c = params.dayOfTheMonth;
            paymentSchedule.bt_stripe__Month_of_Year__c = params.monthOfYear;
            paymentSchedule.bt_stripe__Day_of_Week__c = params.dayOfTheWeek;
            paymentSchedule.bt_stripe__On_The__c = params.onThe;

            //CRON Expression
            paymentSchedule.bt_stripe__CRON__c = params.cron;

            //Logic
            paymentSchedule.bt_stripe__Capture_First__c = params.captureFirst;
            paymentSchedule.bt_stripe__Auto_Capture__c = params.autoCapture;

            insert paymentSchedule;        
        } catch (Exception e) {
            System.debug('Error while creating Payment Schedule: ' + e.getMessage());
        }
    }

    public class InputParameters {

        @InvocableVariable(label='EZ Preset' required=true)
        public String ezPreset;
        
        @InvocableVariable(label='Recurrence Method')
        public String recurrenceMethod;

        @InvocableVariable(label='Start Date' required=true)
        public Date startDate;

        @InvocableVariable(label='End Date')
        public Date endDate;

        @InvocableVariable(label='Count')
        public Integer count;

        @InvocableVariable(label='Opportunity ID')
        public Id opportunityId;

        @InvocableVariable(label='Initial Amount')
        public Decimal initialAmount;

        @InvocableVariable(label='Each Amount')
        public Decimal eachAmount;

        @InvocableVariable(label='Total Amount')
        public Decimal totalAmount;

        @InvocableVariable(label='Currency')
        public String currencyITR;

        @InvocableVariable(label='Description')
        public String description;

        @InvocableVariable(label='Payment Gateway')
        public Id paymentGateway;

        @InvocableVariable(label='Account Related to Payment Schedule')
        public Id accountPs;
        
        @InvocableVariable(label='Contact Related to Payment Schedule')
        public Id contactPs;

        @InvocableVariable(label='Payment Method Related to Payment Schedule')
        public Id paymentMethodPs;

        @InvocableVariable(label='Payment Status')
        public String paymentStatus;

        @InvocableVariable(label='Schedule Status' required=true)
        public String scheduleStatus;

        @InvocableVariable(label='Balance Paid')
        public Decimal balancePaid;

        @InvocableVariable(label='Balance Due')
        public Decimal balanceDue;

        @InvocableVariable(label='Next Payment Date')
        public Date nextPaymentDate;

        @InvocableVariable(label='Repeats')
        public String repeats;
        
        @InvocableVariable(label='Frequency')
        public Integer frequency;

        @InvocableVariable(label='Day of Month')
        public String dayOfTheMonth;

        @InvocableVariable(label='Month of Year')
        public String monthOfYear;

        @InvocableVariable(label='Day of Week')
        public String dayOfTheWeek;

        @InvocableVariable(label='On The')
        public String onThe;

        @InvocableVariable(label='CRON')
        public String cron;

        @InvocableVariable(label='Capture First')
        public Boolean captureFirst;

        @InvocableVariable(label='Auto Capture')
        public Boolean autoCapture;
    }

}