unpackaged/main/default/objects/bt_stripe__Payment_Method__c/bt_stripe__Payment_Method__c.object-meta.xml
<CustomObject>
    <description>A Payment Method record stores information about Credit Cards, Debit Cards and ACH Bank Accounts that are also in your Payment Gateway system. The Payment Method data is PCI compliant because it stores a token instead of raw card or bank data. Payment Methods are related to a Payment Gateway Customer and can be used to create charge Transactions.</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Account_Number__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account_Number__c</fullName>
    <inlineHelpText>The bank account number.</inlineHelpText>
    <label>Account Number</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Expiration_Month__c</fullName>
    <inlineHelpText>The two digit value of the card&#39;s expiration month.</inlineHelpText>
    <label>Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Expiration_Year__c</fullName>
    <inlineHelpText>The two or four digit year of the card&#39;s expiration.</inlineHelpText>
    <label>Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Holder_Name__c</fullName>
    <inlineHelpText>The full name of the card or bank account holder (as displayed on the card or bank account).</inlineHelpText>
    <label>Holder&#39;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/bt_stripe__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>bt_stripe__Payment_Method__c.bt_stripe__Stripe_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.bt_stripe__Customer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>bt_stripe__Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/CreateACHPaymentMethod_Test.cls
@IsTest
public with sharing class CreateACHPaymentMethod_Test {
    @TestSetup
    static void makeData() {
       
        Account testAccount = TestUtility.createAccount('Test Account', 'Mortgage');
        insert testAccount;
       
        Contact testContact = TestUtility.createContact(testAccount.Id, 'Contact');
        insert testContact;

        Opportunity testOpportunity = TestUtility.createOpportunity(testAccount.Id, 'Test Opportunity', 'Qualification', Date.today());
        testOpportunity.Account_Number__c = '“000123456789”';
        testOpportunity.Routing_Number__c = '“110000000”';
        insert testOpportunity;
    }

    @isTest
    static void createACHPaymentMethod_createPaymentMethod_recordCreated() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        List<Opportunity> testOpportunityList = [SELECT Id, AccountId, ContactId FROM Opportunity LIMIT 1];

        List<CreateACHPaymentMethod.InputParameters> inputList = new List<CreateACHPaymentMethod.InputParameters>();
        CreateACHPaymentMethod.InputParameters input = new CreateACHPaymentMethod.InputParameters();
        input.opportunityId = testOpportunityList[0].Id;
        input.paymentMethodRT = Schema.SObjectType.bt_stripe__Payment_Method__c.getRecordTypeInfosByDeveloperName().get('ACH').getRecordTypeId();
        input.cardholderName = 'John Doe';
        input.currencyIso = 'USD';
        input.countryIso = 'US';
        input.accountHolderType = 'Individual';
        input.accountOpp = account.Id;
        input.contactOpp = contact.Id;
        inputList.add(input);

        Test.startTest();
            List<Id> paymentMethodIds = CreateACHPaymentMethod.createPaymentMethod(inputList);
        Test.stopTest();

        assert.areNotEqual(0, paymentMethodIds.size(), 'Expected a payment method ID to be returned');
        
        bt_stripe__Payment_Method__c createdPaymentMethod = [
            SELECT Id, bt_stripe__Card_Holder_Name__c, bt_stripe__Account_Number__c,
                   bt_stripe__Card_Expiration_Month__c, bt_stripe__Card_Expiration_Year__c
            FROM bt_stripe__Payment_Method__c
            WHERE Id = :paymentMethodIds[0]
        ];
        
        assert.areEqual('John Doe', createdPaymentMethod.bt_stripe__Card_Holder_Name__c, 'Cardholder name mismatch');
    }

    @isTest
    static void createACHPaymentMethod_createPaymentMethod_NullOpportunityId() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        List<Opportunity> testOpportunityList = [SELECT Id, AccountId, ContactId FROM Opportunity LIMIT 1];
        Boolean hasError = false;

        List<CreateACHPaymentMethod.InputParameters> inputList = new List<CreateACHPaymentMethod.InputParameters>();
        CreateACHPaymentMethod.InputParameters input = new CreateACHPaymentMethod.InputParameters();
        input.opportunityId = null;
        input.paymentMethodRT = Schema.SObjectType.bt_stripe__Payment_Method__c.getRecordTypeInfosByDeveloperName().get('ACH').getRecordTypeId();
        input.cardholderName = 'John Doe';
        input.currencyIso = 'USD';
        input.countryIso = 'US';
        input.accountHolderType = 'Individual';
        input.accountOpp = account.Id;
        input.contactOpp = contact.Id;
        inputList.add(input);

        Test.startTest();
            try {
                List<Id> paymentMethodIds = CreateACHPaymentMethod.createPaymentMethod(inputList);
            } catch(Exception e) {
                hasError = true;
            }
        Test.stopTest();
        
        assert.isTrue(hasError, 'Expected an error due to invalid expiry data');
    }
}