unpackaged/main/default/objects/bt_stripe__Payment_Method__c/bt_stripe__Payment_Method__c.object-meta.xml
<CustomObject>
    <description>A Payment Method record stores information about Credit Cards, Debit Cards and ACH Bank Accounts that are also in your Payment Gateway system. The Payment Method data is PCI compliant because it stores a token instead of raw card or bank data. Payment Methods are related to a Payment Gateway Customer and can be used to create charge Transactions.</description>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Account__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce Business Account or Person Account related to this Payment Method.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Billing_Postal_Code__c</fullName>
    <inlineHelpText>The billing postal code related to the card. Gateway provider validates addresses only if this setting is turned on (if provider supports).</inlineHelpText>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Expiration_Month__c</fullName>
    <inlineHelpText>The two digit value of the card&#39;s expiration month.</inlineHelpText>
    <label>Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Expiration_Year__c</fullName>
    <inlineHelpText>The two or four digit year of the card&#39;s expiration.</inlineHelpText>
    <label>Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Holder_Name__c</fullName>
    <inlineHelpText>The full name of the card or bank account holder (as displayed on the card or bank account).</inlineHelpText>
    <label>Holder&#39;s Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Card_Number__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Card_Number__c</fullName>
    <inlineHelpText>The full credit or debit card number.</inlineHelpText>
    <label>Number</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Contact__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce Contact related to this Payment Method.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__CVV__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__CVV__c</fullName>
    <inlineHelpText>The CVV Number (&quot;Card Verification Value&quot;) on your credit card or debit card is a 3 digit number on VISA®, MasterCard® and Discover® branded credit and debit cards. On your American Express® branded credit or debit card it is a 4 digit numeric code.</inlineHelpText>
    <label>CVV</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/bt_stripe__Payment_Method__c/fields/bt_stripe__Send_to_Gateway__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Send_to_Gateway__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Payment Methods will process through the Payment Gateway unless this box is checked.</description>
    <inlineHelpText>Payment Methods will process through the Payment Gateway unless this box is checked.</inlineHelpText>
    <label>Send to Gateway</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/bt_stripe__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>bt_stripe__Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>bt_stripe__Payment_Method__c.bt_stripe__Stripe_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.bt_stripe__Customer__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>bt_stripe__Payment_Method__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Number__c</fullName>
    <label>Credit Card Number</label>
    <length>25</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <length>4</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/CreateCreditCardPaymentMethod.cls
public with sharing class CreateCreditCardPaymentMethod {
    @InvocableMethod(label='Create Credit Card Payment Method' description='Creates a Payment Method of type Credit Card')
    public static List<Id> createPaymentMethod(List<InputParameters> inputList) {
        List<Id> paymentMethodIds = new List<Id>();
        
        if (!inputList.isEmpty()) {
            InputParameters input = inputList[0];
            List<EncryptedFieldsResult> encryptedFields = getEncryptedFields(input.opportunityId);

            bt_stripe__Payment_Method__c newPaymentMethod = new bt_stripe__Payment_Method__c();
            newPaymentMethod.RecordTypeId = input.paymentMethodRT;
            newPaymentMethod.bt_stripe__Card_Holder_Name__c = input.cardholderName;
            newPaymentMethod.bt_stripe__Card_Expiration_Month__c = input.expiryMonth;
            newPaymentMethod.bt_stripe__Card_Expiration_Year__c = input.expiryYear;
            newPaymentMethod.bt_stripe__Billing_Postal_Code__c = input.postalCode;
            newPaymentMethod.bt_stripe__Account__c = input.accountOpp;
            newPaymentMethod.bt_stripe__Contact__c = input.contactOpp;
            if (test.isRunningTest()){
                newPaymentMethod.bt_stripe__Send_to_Gateway__c = false;
            } else {
                newPaymentMethod.bt_stripe__Send_to_Gateway__c = true;  
            }
            
            if (!encryptedFields.isEmpty()) {
                EncryptedFieldsResult encryptedData = encryptedFields[0];
                newPaymentMethod.bt_stripe__Card_Number__c = encryptedData.creditCardNumber;
                newPaymentMethod.bt_stripe__CVV__c = encryptedData.cvv;
            }

            if (Schema.sObjectType.bt_stripe__Payment_Method__c.isCreateable()) {
                try {
                    insert newPaymentMethod;
                    paymentMethodIds.add(newPaymentMethod.Id);
                } catch (DmlException e) {
                    throw new FlowException('Error creating Credit Card Payment Method: ' + e.getMessage());
                }
            } else {
                throw new FlowException('You do not have the necessary permissions to create a Credit Card Payment Method.');
            }
        }
        return paymentMethodIds;
    }

    public class InputParameters {
        @InvocableVariable(label='Opportunity ID' description='ID of the related Opportunity' required=true)
        public Id opportunityId;

        @InvocableVariable(label='Credit Card Type' description='Type of credit card' required=true)
        public String cardType;

        @InvocableVariable(label='Holders Name' description='Holders Name' required=true)
        public String cardholderName;

        @InvocableVariable(label='Expiration Month' description='Expiration month of the credit card' required=true)
        public String expiryMonth;

        @InvocableVariable(label='Expiration Year' description='Expiration year of the credit card' required=true)
        public String expiryYear;
        
        @InvocableVariable(label='Payment Method Record Type' description='Type of Payment Method Record Type' required=true)
        public String paymentMethodRT;
        
        @InvocableVariable(label='Postal Code' description='Billing postal code' required=true)
        public String postalCode;
        
        @InvocableVariable(label='Account Related Opportunity' description='The Account associated to the Opportunity' required=true)
        public Id accountOpp;
        
        @InvocableVariable(label='Contact Related Opportunity' description='The Contact associated to the Opportunity' required=true)
        public Id contactOpp;
    }
    
    public class EncryptedFieldsResult {
        public String creditCardNumber;
        public String cvv;
    }
    
   	private static List<EncryptedFieldsResult> getEncryptedFields(Id opportunityId) {
        List<EncryptedFieldsResult> results = new List<EncryptedFieldsResult>();
        
        if (opportunityId == null) {
            return results;
        }

        if (!Schema.sObjectType.Opportunity.isAccessible()) {
            return results;
        }
        
        Schema.DescribeFieldResult creditCardNumberField = Opportunity.Credit_Card_Number__c.getDescribe();
        Schema.DescribeFieldResult cvvField = Opportunity.CVV__c.getDescribe();
        
        if (!creditCardNumberField.isAccessible() ||!cvvField.isAccessible()) {
            return results;
        }
        
        List<Opportunity> opportunities = [
            SELECT Id, 
                   Credit_Card_Number__c, 
                   CVV__c
            FROM Opportunity 
            WHERE Id = :opportunityId
        ];
        
        if (!opportunities.isEmpty()) {
            Opportunity opp = opportunities[0];
            EncryptedFieldsResult result = new EncryptedFieldsResult();
            
            result.creditCardNumber = opp.Credit_Card_Number__c;
            result.cvv = opp.CVV__c;
            
            results.add(result);
        }
        
        return results;
    }
}