unpackaged/main/default/objects/Lead_Distribution_Rule_Criteria__c/Lead_Distribution_Rule_Criteria__c.object-meta.xml
<CustomObject>
    <label>Lead Distribution Rule Criteria</label>
    <nameField>
        <displayFormat>LDRC-{0000}</displayFormat>
        <label>Lead Distribution Rule Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Distribution Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lead_Distribution_Rule_Criteria__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead_Distribution_Rule_Criteria__c/fields/FieldType__c.field-meta.xml
<CustomField>
    <fullName>FieldType__c</fullName>
    <label>FieldType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead_Distribution_Rule_Criteria__c/fields/Lead_Distribution_Rule__c.field-meta.xml
<CustomField>
    <fullName>Lead_Distribution_Rule__c</fullName>
    <label>Lead Distribution Rule</label>
    <referenceTo>LeadDistributionRule__c</referenceTo>
    <relationshipLabel>Lead Distribution Rule Criterias</relationshipLabel>
    <relationshipName>Lead_Distribution_Rule_Criterias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lead_Distribution_Rule_Criteria__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
                <label>Equals</label>
            </value>
            <value>
                <fullName>!=</fullName>
                <label>Not equal to</label>
            </value>
            <value>
                <fullName>&lt;</fullName>
                <label>Less than</label>
            </value>
            <value>
                <fullName>&lt;=</fullName>
                <label>Less than or equal to</label>
            </value>
            <value>
                <fullName>&gt;</fullName>
                <label>Greater than</label>
            </value>
            <value>
                <fullName>&gt;=</fullName>
                <label>Greater than or equal to</label>
            </value>
            <value>
                <fullName>LIKE</fullName>
                <label>Contains</label>
            </value>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Not In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/LeadDistributionRule__c.object-meta.xml
<CustomObject>
    <label>Lead Distribution Rule</label>
    <nameField>
        <label>Lead Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Distribution Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/From_Object__c.field-meta.xml
<CustomField>
    <fullName>From_Object__c</fullName>
    <label>From Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/Logic__c.field-meta.xml
<CustomField>
    <fullName>Logic__c</fullName>
    <label>Logic</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <label>Order By</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/Return_Field__c.field-meta.xml
<CustomField>
    <fullName>Return_Field__c</fullName>
    <label>Return Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/Return_Object__c.field-meta.xml
<CustomField>
    <fullName>Return_Object__c</fullName>
    <label>Return Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LeadDistributionRule__c/fields/Sorting_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Direction__c</fullName>
    <label>Sorting Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASC</fullName>
            </value>
            <value>
                <fullName>DESC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LeadDistributionControllerTest.cls
@isTest
public class LeadDistributionControllerTest {
    
    @testSetup
    static void setupTestData() {
        LeadDistributionRule__c rule1 = new LeadDistributionRule__c(
            Name = 'Test Rule 1',
            From_Object__c = 'Account',
            Return_Object__c = 'Account',
            Return_Field__c = 'Id',
            IsActive__c = true,
            Priority__c = 1,
            Logic__c = '{1} AND {2}',
            Order_By__c = 'CreatedDate',
            Sorting_Direction__c = 'DESC'
        );
        insert rule1;
        
        
        List<Lead_Distribution_Rule_Criteria__c> criteria =  new List<Lead_Distribution_Rule_Criteria__c>();

        Lead_Distribution_Rule_Criteria__c criterion1 = new Lead_Distribution_Rule_Criteria__c(
            Lead_Distribution_Rule__c = rule1.Id,
            Field__c = 'AccountSource',
            Operator__c = '=',
            Value__c = 'Website',
            Order__c = 1,
            FieldType__c = 'Text'
        );
        criteria.add(criterion1);

        Lead_Distribution_Rule_Criteria__c criterion2 = new Lead_Distribution_Rule_Criteria__c(
            Lead_Distribution_Rule__c = rule1.Id,
            Field__c = 'Site',
            Operator__c = '=',
            Value__c = 'Federal',
            Order__c = 2,
            FieldType__c = 'Text'
        );
        criteria.add(criterion2);
     
        insert criteria;
    }

    @IsTest
    static void testFetchRecordForDistribution() {
        
        insert new Lead(FirstName = 'Matching', LastName = 'Lead', Company = 'Test Company', IsConverted = false);
        insert new Account(FirstName = 'Matching', LastName = 'Account', AccountSource = 'Website', Site = 'Federal');

        sObject result;

        Test.startTest();
        result = LeadDistributionController.fetchRecordForDistribution();
        Test.stopTest();

        System.assertNotEquals(null, result, 'A lead should have been returned.');
        System.assert(result instanceof Account, 'The returned object should be an Account.');
    }
    

}